#ifndef _REMOTE_ID_H
#define _REMOTE_ID_H

enum RemoteId
{
    REMOTE_DATA_POINT_ID,
    REMOTE_NOTIFICATION_ID,
    REMOTE_DATA_POINT_JSON_ID,
    REMOTE_NOTIFICATION_JSON_ID,
    REMOTE_SYSTEM_MODE_CHANGED_ID
};

#endif